### ISSUE TITLE
max retries exceeded for large datasets

### ISSUE THREAD

**Issue by aishwarya-parameshwaran** [chrismattmann/tika-similarity#58]
When I tried to run edit-value-similarity.py and cosine_similarity.py on a large dataset, it gives a ConnectionError stating Max retries exceeded.
Temporarily I fixed it by adding a time.sleep wherever a request is being made as follows:

```python
        try:
            filename_list = [filename for filename in filename_list if parser.from_file(filename)]
        except ConnectionError:
            sleep(1)
```
```python 
       try:
           row_edit_distance = [file1, file2]            

            file1_parsedData = parser.from_file(file1)
            file2_parsedData = parser.from_file(file2)
    
            intersect_features = set(file1_parsedData["metadata"].keys()) & set(file2_parsedData["metadata"].keys())                
            intersect_features = [feature for feature in intersect_features if feature not in na_metadata ]

            file_edit_distance = 0.0
            for feature in intersect_features:

                file1_feature_value = stringify(file1_parsedData["metadata"][feature])
                file2_feature_value = stringify(file2_parsedData["metadata"][feature])

                if len(file1_feature_value) == 0 and len(file2_feature_value) == 0:
                    feature_distance = 0.0
                else:
                    feature_distance = float(editdistance.eval(file1_feature_value, file2_feature_value))/(len(file1_feature_value) if len(file1_feature_value) > len(file2_feature_value) else len(file2_feature_value))
                    
                file_edit_distance += feature_distance

            
            if allKeys:
                file1_only_features = set(file1_parsedData["metadata"].keys()) - set(intersect_features)
                file1_only_features = [feature for feature in file1_only_features if feature not in na_metadata]

                file2_only_features = set(file2_parsedData["metadata"].keys()) - set(intersect_features)
                file2_only_features = [feature for feature in file2_only_features if feature not in na_metadata]

                file_edit_distance += len(file1_only_features) + len(file2_only_features)       # increment by 1 for each disjunct feature in (A-B) & (B-A), file1_disjunct_feature_value/file1_disjunct_feature_value = 1
                file_edit_distance /= float(len(intersect_features) + len(file1_only_features) + len(file2_only_features))

            else:
                file_edit_distance /= float(len(intersect_features))    #average edit distance

            row_edit_distance.append(1-file_edit_distance)
            a.writerow(row_edit_distance)
      except ConnectionError:
            sleep(1)
```    
I added the same try except block for the acceptTypes block and anywhere else tika parser is being called.
Should I submit a pull request to fix this issue?

**Comment by mit2nil** [comment]
Hi,

I am also getting same error for both cosine and edit distance:
C:\stuff\Git\tika-similarity>c:\Python27\python cosine_similarity.py --inputDir "data\application_dif+xml" --outCSV cosine_gif.csv
Accepting all MIME Types.....
Traceback (most recent call last):
  File "cosine_similarity.py", line 74, in <module>
    computeScores(args.inputDir, args.outCSV, args.accept)
  File "cosine_similarity.py", line 54, in computeScores
    file2_parsedData = parser.from_file(file2)
  File "c:\Python27\lib\site-packages\tika\parser.py", line 25, in from_file
    jsonOutput = parse1('all', filename, serverEndpoint)
  File "c:\Python27\lib\site-packages\tika\tika.py", line 151, in parse1
    verbose, tikaServerJar)
  File "c:\Python27\lib\site-packages\tika\tika.py", line 256, in callServer
    resp = verbFn(serviceUrl, encodedData, headers=headers)
  File "c:\Python27\lib\site-packages\requests\api.py", line 120, in put
    return request('put', url, data=data, **kwargs)
  File "c:\Python27\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "c:\Python27\lib\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9998): Max retries exceeded with url: /rmeta/text (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x02DE5CD0>: Failed to establish a new connection: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted',))

**Comment by SharmileeS** [comment]
```
Traceback (most recent call last):
  File "edit-value-similarity.py", line 104, in <module>
    computeScores(args.inputDir, args.outCSV, args.accept, args.allKeys)
  File "edit-value-similarity.py", line 45, in computeScores
    filename_list = [filename for filename in filename_list if parser.from_file(filename)]
  File "build/bdist.macosx-10.9-x86_64/egg/tika/parser.py", line 25, in from_file
  File "build/bdist.macosx-10.9-x86_64/egg/tika/tika.py", line 151, in parse1
  File "build/bdist.macosx-10.9-x86_64/egg/tika/tika.py", line 256, in callServer
  File "C:\Python275\lib\site-packages\requests-2.9.1-py2.7.egg\requests\api.py", line 120, in put
    return request('put', url, data=data, **kwargs)
  File "C:\Python275\lib\site-packages\requests-2.9.1-py2.7.egg\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python275\lib\site-packages\requests-2.9.1-py2.7.egg\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python275\lib\site-packages\requests-2.9.1-py2.7.egg\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python275\lib\site-packages\requests-2.9.1-py2.7.egg\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9998): Max retries exceeded with url: /rmeta/text (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x00000000034E70B8>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
```

Getting this error for cosine and edit distance when running on large dataset.

**Comment by chrismattmann** [comment]
fixed in #61

**Comment by mit2nil** [comment]
I am still getting the connectionError after pulling in latest fix.
...
tika.py: Warn: Tika server returned status: 422
tika.py: Warn: Tika server returned status: 422
tika.py: Warn: Tika server returned status: 422
tika.py: Warn: Tika server returned status: 422
tika.py: Warn: Tika server returned status: 422
tika.py: Warn: Tika server returned status: 422
tika.py: Warn: Tika server returned status: 422
tika.py: Warn: Tika server returned status: 422
tika.py: Warn: Tika server returned status: 422
tika.py: Warn: Tika server returned status: 422
tika.py: Warn: Tika server returned status: 422
Traceback (most recent call last):
  File "edit-value-similarity.py", line 111, in <module>
    computeScores(args.inputDir, args.outCSV, args.accept, args.allKeys)
  File "edit-value-similarity.py", line 47, in computeScores
    filename_list = [filename for filename in filename_list if "metadata" in parser.from_file(filename)]
  File "C:\Python27\lib\site-packages\tika\parser.py", line 25, in from_file
    jsonOutput = parse1('all', filename, serverEndpoint)
  File "C:\Python27\lib\site-packages\tika\tika.py", line 151, in parse1
    verbose, tikaServerJar)
  File "C:\Python27\lib\site-packages\tika\tika.py", line 256, in callServer
    resp = verbFn(serviceUrl, encodedData, headers=headers)
  File "C:\Python27\lib\site-packages\requests\api.py", line 120, in put
    return request('put', url, data=data, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9998): Max retries exceeded with url: /rmeta/text (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03B762B0>: Failed to establish a new connection: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted',))

**Comment by chrismattmann** [comment]
hmm that's odd?

**Comment by aishwarya-parameshwaran** [comment]
I guess line 47 needs a try except block as well. I just made that change and tried running. It seems to have solved the problem.

**Comment by chrismattmann** [comment]
fixed in #62

**Comment by chrismattmann** [comment]
@aishwarya-parameshwaran thank you! Please feel free to send a PR that updates your name in the Contributor list in README.md
